#! /usr/local/bin/perl
#
# ----------------------------------------------------------------------
#     T-Kernel 2.0 Software Package
#
#     Copyright 2011 by Ken Sakamura.
#     This software is distributed under the T-License 2.0.
# ----------------------------------------------------------------------
#
#     Released by T-Engine Forum(http://www.t-engine.org/) at 2011/05/17.
#
# ----------------------------------------------------------------------
#

#	mergesrec
#
#	merge S-Record format files to one file
#
#

$usage = "usage: mergesrec file ... > out\n";

$top = "";
$end = "";

while ( <> ) {
	if ( /^S0/ ) {
		if ( $top eq "" ) {
			$top = $_;
			print;
		}
		next;
	}
	if ( /^S7/ ) {
		$end = $_;
		next;
	}
	print;
}

print $end;

exit 0;


