#
# ----------------------------------------------------------------------
#     T-Kernel 2.0 Software Package
#
#     Copyright 2011 by Ken Sakamura.
#     This software is distributed under the T-License 2.0.
# ----------------------------------------------------------------------
#
#     Released by T-Engine Forum(http://www.t-engine.org/) at 2011/05/17.
#
# ----------------------------------------------------------------------
#

#
#	Makefile for gmake
#	crt0 - C startup routine (common description)
#

# source file dependencies (generated automatically)
DEPS = Dependencies
DEPENDENCIES_OUTPUT := $(DEPS)

# ----------------------------------------------------------------------------

# source file path
S = ../../src
VPATH = $(S) $(S)/sysdepend/$(TETYPE)_$(MACHINE)
HEADER += $(S) $(S)/sysdepend/$(TETYPE)_$(MACHINE)

# ----------------------------------------------------------------------------

.PHONY: all clean install

all: $(TARGET)

install: $(TARGET:%=$(LIB_INSTALLDIR)/%)

clean:
	$(RM) $(TARGET) $(DEPS)

# generate dependencies
ifdef DEPENDENCIES_OUTPUT
  $(DEPS): ; touch $(DEPS)
else
  $(DEPS): $(SRC) ; $(MAKEDEPS) $@ $?
endif
-include $(DEPS)
