#
# ----------------------------------------------------------------------
#     T-Kernel 2.0 Software Package
#
#     Copyright 2011 by Ken Sakamura.
#     This software is distributed under the T-License 2.0.
# ----------------------------------------------------------------------
#
#     Released by T-Engine Forum(http://www.t-engine.org/) at 2011/05/17.
#
# ----------------------------------------------------------------------
#

#
#	Makefile for gmake
#	usermain (included from sysmain)
#

# source files
SRC += usermain.c

# source file path
VPATH += ../../../usermain
HEADER += ../../../usermain

# Manager and Driver objects
I_OBJ +=

# additional libraries
LDUSRLIBS += -lstr
